#!/usr/bin/env python3
"""Convert extras/dashboard.html to src/dashboard_html.c for ESP-IDF.

Outputs a plain C file (no Arduino/PROGMEM dependencies).
Skips writing if content is unchanged to avoid unnecessary rebuilds.

Usage: html_to_header_idf.py <input.html> <output.c>
"""
import sys
import os
import gzip
import hashlib
from pathlib import Path


def main() -> int:
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <input.html> <output.c>", file=sys.stderr)
        return 1

    input_path  = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    if not input_path.exists():
        print(f"[html_to_header_idf] ERROR: {input_path} not found", file=sys.stderr)
        return 1

    html_bytes   = input_path.read_bytes()
    if not html_bytes:
        print(f"[html_to_header_idf] ERROR: {input_path} is empty", file=sys.stderr)
        return 1
    compressed   = gzip.compress(html_bytes, compresslevel=9)
    content_hash = hashlib.md5(html_bytes).hexdigest()[:8]

    # Build hex array string
    rows = []
    for i in range(0, len(compressed), 16):
        chunk = compressed[i:i + 16]
        rows.append("    " + ", ".join(f"0x{b:02x}" for b in chunk))

    c_content = (
        "/* Auto-generated by html_to_header_idf.py — DO NOT EDIT */\n"
        f"/* Source: {input_path.name}, hash: {content_hash}, "
        f"original: {len(html_bytes)} B, compressed: {len(compressed)} B */\n"
        "#include <stdint.h>\n"
        "#include <stddef.h>\n"
        "\n"
        "const uint8_t DASHBOARD_HTML_DATA[] = {\n"
        + ",\n".join(rows) + "\n"
        "};\n"
        "\n"
        "const size_t DASHBOARD_HTML_SIZE = sizeof(DASHBOARD_HTML_DATA);\n"
    )

    # Only write if changed (avoids triggering CMake rebuild unnecessarily)
    if output_path.exists() and output_path.read_text(encoding="utf-8") == c_content:
        print(f"[html_to_header_idf] No change: {output_path}")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(c_content, encoding="utf-8")
    print(f"[html_to_header_idf] Written: {output_path} "
          f"({len(html_bytes)} -> {len(compressed)} bytes, {100*(1-len(compressed)/len(html_bytes)):.1f}% compression)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
